# Generated by Django 4.1.6 on 2023-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MAKEUP', 'MakeUp'), ('HAIR', 'HairCare'), ('LIPS', 'LipsCare'), ('EYE', 'EyeShadow'), ('NAIL', 'Nails'), ('FOOT', 'FootCare'), ('FACE', 'FaceProducts')], max_length=50)),
                ('product_name', models.ImageField(upload_to='product')),
            ],
        ),
    ]
