# Generated by Django 4.1.4 on 2023-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
