# Generated by Django 4.1.4 on 2023-03-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userdata_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
