# Generated by Django 4.1.7 on 2023-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartitems_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
