# Generated by Django 4.1.7 on 2023-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cartitems_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=100)),
                ('min_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
