# Generated by Django 4.1.7 on 2023-03-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
