# Generated by Django 4.1.7 on 2023-03-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_products_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discounted_price',
        ),
    ]
