# Generated by Django 4.1.7 on 2023-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.RemoveField(
            model_name='category',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MAKEUP', 'MakeUp'), ('HAIR', 'HairCare'), ('LIPS', 'LipsCare'), ('EYE', 'EyeShadow'), ('NAIL', 'Nails'), ('FOOT', 'FootCare'), ('FACE', 'FaceProducts')], default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
