# Generated by Django 4.1.7 on 2023-03-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
