# Generated by Django 4.2.4 on 2023-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(default=None, null=True, upload_to='profile'),
        ),
    ]
