# Generated by Django 4.2.4 on 2023-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='hierarchy_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
