# Generated by Django 4.2.4 on 2023-08-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0002_alter_cartitems_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='products.products'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
