# Generated by Django 4.2.4 on 2023-08-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('MAKEUP', 'MakeUp'), ('HAIR', 'HairCare'), ('LIPS', 'LipsCare'), ('EYE', 'EyeShadow'), ('NAIL', 'Nails'), ('FOOT', 'FootCare'), ('FACE', 'FaceProducts')], max_length=30, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('product_image', models.ImageField(default=None, null=True, upload_to='product')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.sellers')),
            ],
        ),
    ]
