# Generated by Django 4.2.4 on 2023-09-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
